---
title: "Advanced Analytics of Financve"
output: html_notebook
author: "Elina Harutyunyan"
---

```{r, warning=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(forecast)
library(fGarch)
library(ModelMetrics)
library(lmtest)
cpi <- read.csv("/Users/elinaharutyunyan/Desktop/MFin Spring 2020/Advanced Analytics of Finance/Assignment 5/CPI.csv")
cpi$DATE <- as.Date(cpi$DATE, format = "%Y-%m-%d")
```

Question 1
```{r}
cpi <- mutate(cpi, pi = log(CPIAUCSL/dplyr::lag(CPIAUCSL)))

ggplot(cpi %>% drop_na()) + geom_line(aes(x = DATE, y = pi)) + theme_light() + xlab("Date") + ylab("Monthly Inflation")

cpi <- cpi %>% drop_na()

acf(cpi$pi, lag.max = 12)

#auto arima gives you AR(15) as optimal for AIC and AR(5) for BIC
auto.arima(cpi$pi, max.p = 20, max.q = 0,max.d = 0, ic = 'aic')
auto.arima(cpi$pi, max.p = 20, max.q = 0,max.d = 0, ic = 'bic')

#negative log likelihood and positive penalty. minimize the value for a given lag order
aic <- c()
bic <- c()
for (i in 1:20){
  ar <- arima(cpi$pi, order = c(i,0,0))
  aic[i] <- AIC(ar)
  bic[i] <- BIC(ar)
}

aic_df <- as.data.frame(cbind(c(1:20),aic))
aic_df[which(aic_df$aic == min(aic)),]$V1

bic_df <- as.data.frame(cbind(c(1:20),bic))
bic_df[which(bic_df$bic == min(bic)),]$V1


plot(aic, type = "l")
plot(bic, type = "l")

```

Question 2

```{r}
wmt <- read.csv('/Users/elinaharutyunyan/Desktop/MFin Spring 2020/Advanced Analytics of Finance/Assignment 5/WMT.csv')

wmt$NI <- log(wmt$NI)
wmt <- mutate(wmt, ni_dif = NI - dplyr::lag(NI), ni_dif4 = NI - dplyr::lag(NI, n = 4))

ggplot(wmt %>% drop_na()) + geom_line(aes(x = as.Date(as.character(datadate), format = "%Y%m%d"), y = ni_dif)) + xlab("Date") + ylab("First Difference of Net Income") + theme_light()

ggplot(wmt %>% drop_na()) + geom_line(aes(x = as.Date(as.character(datadate), format = "%Y%m%d"), y = ni_dif4)) + xlab("Date") + ylab("Seasonal Difference of Net Income") + theme_light()


wmt$Fiscal.Quarter <- as.character(wmt$Fiscal.Quarter)
wmt_train <- wmt[which(wmt$Fiscal.Quarter <= '2014Q4'),]
wmt_test <- wmt[which(wmt$Fiscal.Quarter > '2014Q4'),]

wmt_arima <- arima(wmt_train$ni_dif, order = c(0,0,1))
coeftest(wmt_arima)
#check this part of prediction
pred_arima <- predict(wmt_arima,nrow(wmt_test))$pred

wmt_airline <- arima(wmt_train$ni_dif, order = c(0,1,1), seasonal = list(order = c(0,1,1),period = 4))
coeftest(wmt_airline)

pred_airline <- predict(wmt_airline,nrow(wmt_test))$pred

mse(pred_arima[c(-14,-15)],wmt_test$ni_dif[c(-14,-15)])

mse(pred_airline[c(-14,-15)],wmt_test$ni_dif[c(-14,-15)])

#plot forecasting error for both models, graph in lecture
fr_error_arima <- wmt_test$ni_dif[c(-14,-15)]-pred_arima[c(-14,-15)]
fr_error_airline <- wmt_test$ni_dif[c(-14,-15)]-pred_airline[c(-14,-15)]
test_dates <- as.Date(as.character(wmt_test$datadate),format = "%Y%m%d")

ggplot() + geom_line(aes(x = test_dates, y = pred_arima)) + theme_light() + xlab("Date") + ylab("Forecast") 

ggplot() + geom_line(aes(x = test_dates, y = pred_airline)) + theme_light() + xlab("Date") + ylab("Forecast") 

ggplot() + geom_line(aes(x =test_dates[c(-14,-15)], y = fr_error_arima, col = "ARIMA(0,1,1)")) + theme_light() + theme(legend.title = element_blank()) + xlab("Date") + ylab(" ") + ggtitle("Forecasting Error")+ scale_color_manual(values = c("royalblue","maroon")) + geom_line(aes(x = test_dates[c(-14,-15)], y = fr_error_airline, col = "Airline Model"))

```

Question 3
```{r}
nav <- read.csv("/Users/elinaharutyunyan/Desktop/MFin Spring 2020/Advanced Analytics of Finance/Assignment 5/NAV.csv")
mkt <- read.csv("/Users/elinaharutyunyan/Desktop/MFin Spring 2020/Advanced Analytics of Finance/Assignment 4/F-F_Research_Data_Factors_daily 2.CSV")
mkt$date <- as.Date(as.character(mkt$date),format = "%Y%m%d")
colnames(mkt)[1]<-"Date"
nav$X <- as.character(nav$X)
nav$X <- as.Date(nav$X, format = "%Y%m%d")
colnames(nav)[1]<-"Date"

nav <- mutate(nav, ret = NAV/dplyr::lag(NAV)-1)
nav <- nav %>% drop_na()

mkt$Mkt.RF<-mkt$Mkt.RF/100
mkt$RF <- mkt$RF/100

nav_df <- merge(nav[,c(1,3)], mkt[,c(1,2,5)], by = "Date")
nav_df <- mutate(nav_df, exret = ret-RF)

#sharpe ratio
mean(nav_df$exret)/sd(nav_df$exret)*sqrt(252)

#information ratio
mean(nav_df$ret-nav_df$Mkt.RF-nav_df$RF)/sd(nav_df$ret-nav_df$Mkt.RF-nav_df$RF)*sqrt(252)

#CAPM
capm <- lm(exret ~ Mkt.RF, data = nav_df)
summary(capm)$coefficients[1,1]*252*100

#monthly realized volatility for the portfolio
nav_df$month <- format(as.Date(nav_df$Date), "%Y-%m")

realized_vol <- nav_df %>% dplyr::group_by(month) %>% summarise(vol = sd(ret)*sqrt(n()))

plot(realized_vol$vol, type = "l",xlab = "Month",ylab = "Realized Volatility")

#fitting AR(1)-GARCH(1,1) model
mod_garch = garchFit(~ 1 + arma(1,0) + garch(1,1), data = nav_df$ret, trace = FALSE)
summary(mod_garch)
round(mod_garch@fit$matcoef,5)

#VAR 1-day
mu <-mod_garch@fit$par[1]
phi1 <-mod_garch@fit$par[2]
a0 <- mod_garch@fit$par[3]
a1 <- mod_garch@fit$par[4]
b1 <- mod_garch@fit$par[5]


nav_test = nav_df[which(nav_df$Date >= "2002-01-01"),]

r <- c()
sigma <- c()
x <- c()
#initial value of returns at t-1
r[1] <- nav_df$ret[which(nav_df$Date == "2001-12-31")]
#initial value of sigma
sigma[1] = sqrt(a0 / (1-a1-b1))
#initial value of x as the residual value of realized returns and the predicted returns
x[1] <- nav_df$ret[which(nav_df$Date == "2001-12-31")] - mu - phi1*nav_df$ret[which(nav_df$Date == 	"2001-12-28")]

for (i in 2:nrow(nav_test)){
  r[i] = mu + phi1*nav_test$ret[i-1]
  x[i] =  nav_test$ret[i] - r[i]
  sigma[i] = sqrt(a0 + a1*x[i-1]^2 + b1*sigma[i-1]^2)
}

nav_test <- merge(nav_test, nav[,c(1,2)], by = "Date")
nav_test <- cbind(nav_test,x,r,sigma)

nav_test <- mutate(nav_test, var1 = NAV*(r + qnorm(0.01)*sigma))
nav_test <- mutate(nav_test, var10 = var1*sqrt(10))


ggplot(nav_test) + geom_line(aes(x=Date, y = var1, col = "VaR 1-Day")) + 
  geom_line(aes(x=Date, y=var10, col = "VaR 10-Day")) + scale_color_manual(values = c("royalblue", "indianred")) + labs(color = "Value at Risk") + ggtitle("1-Day and 10-Day Value at Risk") + xlab("Date") + ylab("VaR") + theme_light()
```





